#ifndef CORTEX_CONSTANTS_H
#define CORTEX_CONSTANTS_H

// equivalent to MPIR_CVAR_ALLGATHER_LONG_MSG_SIZE in Mpich
#define CORTEX_ALLGATHER_LONG_MSG_SIZE 		524288

// equivalent of MPIR_CVAR_ALLGATHER_SHORT_MSG_SIZE in Mpich
#define CORTEX_ALLGATHER_SHORT_MSG_SIZE 	81920

// equivalent of MPIR_CVAR_ALLGATHERV_PIPELINE_MSG_SIZE in Mpich
#define CORTEX_ALLGATHERV_PIPELINE_MSG_SIZE 	32768

// equivalent of MPIR_CVAR_ALLREDUCE_SHORT_MSG_SIZE in Mpich
#define CORTEX_ALLREDUCE_SHORT_MSG_SIZE		2048

// equivalent of MPIR_CVAR_ALLTOALL_THROTTLE in Mpich
#define CORTEX__ALLTOALL_THROTTLE		32

#endif
